name: pdfcraft_form
description: "Form engine, expression evaluation, and data binding for the PDFCraft ecosystem."
version: 1.1.4
homepage: https://github.com/rajarajanponraj/pdfcraft
repository: https://github.com/rajarajanponraj/pdfcraft/tree/main/packages/pdfcraft_form
issue_tracker: https://github.com/rajarajanponraj/pdfcraft/issues

funding:
  - https://ko-fi.com/rajarajanp
  - https://www.paypal.com/ncp/payment/8UD5B3C8LH8HJ

environment:
  sdk: ^3.3.0
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  pdfcraft_core: ^1.1.3
  petitparser: ^7.0.2
  pdfcraft_generator: ^1.2.3
  pdf: ^3.10.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.3.0

flutter:
